server:
  port: 8100

esb:
  dataPubKey: MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQC4EuSmFLvF-tpRg*XGzIeQDUc993Fk6DNtgmUEtL1jsjFABfOFwzLzj07AMniahLtqbvZdvdSWMjySCVM-7Tmu3uQnf8YvDdSJ3PRLehKEz42RLzMv1q3K93dMfCzD8UCaLFe2x-9JugNPVQxWWNWlsHmJuekb548iBst6Z2x6AQIDAQAB
  signPrvKey: MIICdgIBADANBgkqhkiG9w0BAQEFAASCAmAwggJcAgEAAoGBAKr0SS4ewZhwynrEr2iIwwix-BzXa7otDKkmfP4Z7z4tq*Uvlr3vCVbW96jVFLy948XOeO1Lq0ZaK9y*b*kmPekgfjclTS8yB5cgTGD48t7kSUAMsDCmicnVV-8JMXB32C*YQFAP219ihOWM9cxml8jQwwbsg*3v6AWZzHl6sFmrAgMBAAECgYAvLiIwN07IqoBHJ5cda3kgIjbpIs7ZX*t5l2SxoCi16VbidqLMonbaX5OUJdKGUIXXJqebHeIUFXi7gFdUajh1dOkKjemC2k5VYE0Wx5gSuOB*cdelPD4e628TdNH3ETLrH4IhDjvAGyj5fxWPhZH*uZpZ2Pjqh5oKxh-lnQk4yQJBAPB5kKFBrG89*pTeIMOlCkk8dfuuJ65ZOChdiVhoS-yLd0LzaHgRxy7O1yOsjSdY3t*M*7FJFYbNasORytSlhSUCQQC1-bkAV8K9G-Z-TvShoA9GH8A5iw6XE0vyOAfGBk1-P7GpJN6kgBbH4uLjMS1P9D*Qd-6H4*fRFXnQSg6VhvKPAkEAnApl-R1*ZNjU5xCUNh*74vXmoR-LA*lE9XxsiP90fzWId9s2aOMwWoFBPRbUqTmTtX-oOovv*f8FTk4mTYHyOQJAQtUJEkIoRpA1Rm01UwFXepYAXmFdm0c-1ZST7jm0Te2TDZ13kYtkUkVUssAFdt4oVaJrO3YLVHIBiOcZUfn7qwJAJloNWu2lc3kCPNag0lSwcYyO*woIOkDsQ9RWrSSYWp4bwMP*tqA-kK6sZ30XIieIVG6t*Q6eivxc5DSC9hJ7UA==
  routeUrl: http://hrfax.imwork.net:8998/bank/route
  # routeUrl: http://192.168.0.36:8998/bank/route

fs:
  storage:
    local:
      temp: D:/cardry/tmp